[package]
name = "gateway-migration"
edition = { workspace = true }
version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
sea-orm-migration = { workspace = true }
async-trait = { workspace = true }
